services:
  # ====== Zookeeper ======
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # ====== Kafka ======
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Single listener on port 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Single-broker dev setup
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # ====== MongoDB (NoSQL store) ======
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ====== API Gateway (FastAPI service) ======
  api-gateway:
    build:
      context: ../backend/services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - kafka
      - mongo

  ingestion-service:
    build:
      context: ../backend/services/ingestion-service
      dockerfile: Dockerfile
    container_name: ingestion-service
    restart: always
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BROKER=kafka:9092
      - NEWS_RAW_TOPIC=news.raw
    depends_on:
      - kafka

  normalization-service:
    build:
      context: ../backend/services/normalization-service
      dockerfile: Dockerfile
    container_name: normalization-service
    restart: always
    ports:
      - "8002:8002"   # so you can hit its /health from host
    environment:
      - KAFKA_BROKER=kafka:9092
      - NEWS_RAW_TOPIC=news.raw
      - NEWS_NORMALIZED_TOPIC=news.normalized
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=news_analytics
      - MONGO_ARTICLES_COLLECTION=articles_normalized
    depends_on:
      - kafka
      - mongo

  # ====== Nginx (load balancer / reverse proxy) ======
  nginx:
    image: nginx:1.27
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway

volumes:
  mongo_data:
